### PR TITLE
Move AMA to Completed

### PR DESCRIPTION
**Pull request by mikhailnathanielabordo**

### CODE REVIEW

**Comment by atherdon** [comment]
We didn't send this template(yet) via Amazon SES, so we shouldn't mark it as completed.

**Comment by mikhailnathanielabordo** [comment]
I see. will just remain here until it was sent then. thanks. 🙇

**Comment by atherdon** [comment]
if you kick my ass to move it forward - we can do it - I just stuck with other work. So it depends on you :)

**Review by atherdon — APPROVED** [review]
i'm not sure who want to lead this part. I'm stepping back

**Pull request merged**
