### PR TITLE
Wc template

### PR DESCRIPTION
**Pull request by mikhailnathanielabordo**

### CODE REVIEW

**Review by atherdon — COMMENTED** [review]
should i merge it?

**Comment by mikhailnathanielabordo** [comment]
> should i merge it?

yup. I think it's ok now. 🙇

**Review by atherdon — APPROVED** [review]

**Comment by atherdon** [comment]
@mikhailnathanielabordo do you think we should send it today? I mean if we have 3 letters this week - we don't have much time to think about dates. We also don't have more than 90k emails per day from SES

**Comment by mikhailnathanielabordo** [comment]
sure. no problem for me.

**Comment by atherdon** [comment]
@mikhailnathanielabordo can you move it into Sendy then. I'll check time and hit send when it's the best time for USA

**Comment by atherdon** [comment]
@mikhailnathanielabordo hold on we cant send it yet. will need to take a look with clean eyes on it.
will review template tomorrow and buzz you with my feedabck

**Pull request merged**
